// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/MiniMsgRpc.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MiniMsgGrpc {
  public static partial class MiniMsgGreeter
  {
    static readonly string __ServiceName = "MiniMsgGrpc.MiniMsgGreeter";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::MiniMsgGrpc.MsgRequest> __Marshaller_MiniMsgGrpc_MsgRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MiniMsgGrpc.MsgRequest.Parser));
    static readonly grpc::Marshaller<global::MiniMsgGrpc.MsgReply> __Marshaller_MiniMsgGrpc_MsgReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::MiniMsgGrpc.MsgReply.Parser));

    static readonly grpc::Method<global::MiniMsgGrpc.MsgRequest, global::MiniMsgGrpc.MsgReply> __Method_RepMsg = new grpc::Method<global::MiniMsgGrpc.MsgRequest, global::MiniMsgGrpc.MsgReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RepMsg",
        __Marshaller_MiniMsgGrpc_MsgRequest,
        __Marshaller_MiniMsgGrpc_MsgReply);

    static readonly grpc::Method<global::MiniMsgGrpc.MsgRequest, global::MiniMsgGrpc.MsgReply> __Method_PushMsg = new grpc::Method<global::MiniMsgGrpc.MsgRequest, global::MiniMsgGrpc.MsgReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "PushMsg",
        __Marshaller_MiniMsgGrpc_MsgRequest,
        __Marshaller_MiniMsgGrpc_MsgReply);

    static readonly grpc::Method<global::MiniMsgGrpc.MsgRequest, global::MiniMsgGrpc.MsgReply> __Method_PollMsg = new grpc::Method<global::MiniMsgGrpc.MsgRequest, global::MiniMsgGrpc.MsgReply>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "PollMsg",
        __Marshaller_MiniMsgGrpc_MsgRequest,
        __Marshaller_MiniMsgGrpc_MsgReply);

    static readonly grpc::Method<global::MiniMsgGrpc.MsgRequest, global::MiniMsgGrpc.MsgReply> __Method_RouteMsg = new grpc::Method<global::MiniMsgGrpc.MsgRequest, global::MiniMsgGrpc.MsgReply>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "RouteMsg",
        __Marshaller_MiniMsgGrpc_MsgRequest,
        __Marshaller_MiniMsgGrpc_MsgReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MiniMsgGrpc.MiniMsgRpcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MiniMsgGreeter</summary>
    [grpc::BindServiceMethod(typeof(MiniMsgGreeter), "BindService")]
    public abstract partial class MiniMsgGreeterBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::MiniMsgGrpc.MsgReply> RepMsg(global::MiniMsgGrpc.MsgRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task PushMsg(global::MiniMsgGrpc.MsgRequest request, grpc::IServerStreamWriter<global::MiniMsgGrpc.MsgReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MiniMsgGrpc.MsgReply> PollMsg(grpc::IAsyncStreamReader<global::MiniMsgGrpc.MsgRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task RouteMsg(grpc::IAsyncStreamReader<global::MiniMsgGrpc.MsgRequest> requestStream, grpc::IServerStreamWriter<global::MiniMsgGrpc.MsgReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MiniMsgGreeterBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RepMsg, serviceImpl.RepMsg)
          .AddMethod(__Method_PushMsg, serviceImpl.PushMsg)
          .AddMethod(__Method_PollMsg, serviceImpl.PollMsg)
          .AddMethod(__Method_RouteMsg, serviceImpl.RouteMsg).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MiniMsgGreeterBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RepMsg, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MiniMsgGrpc.MsgRequest, global::MiniMsgGrpc.MsgReply>(serviceImpl.RepMsg));
      serviceBinder.AddMethod(__Method_PushMsg, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::MiniMsgGrpc.MsgRequest, global::MiniMsgGrpc.MsgReply>(serviceImpl.PushMsg));
      serviceBinder.AddMethod(__Method_PollMsg, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::MiniMsgGrpc.MsgRequest, global::MiniMsgGrpc.MsgReply>(serviceImpl.PollMsg));
      serviceBinder.AddMethod(__Method_RouteMsg, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::MiniMsgGrpc.MsgRequest, global::MiniMsgGrpc.MsgReply>(serviceImpl.RouteMsg));
    }

  }
}
#endregion
